# Replace one subject with 2 new subjects
DELETE {
  GRAPH ?G {
    ?OLDS ?P ?O .
  }
}
INSERT {
  GRAPH ?G {
    ?NEWS  ?P ?O .
    ?NEWS2 ?P ?O .
  }
}
WHERE {
  BIND ( <http://semantic-forms.cc:1952/ldp/Inventaire_Saint_Didier_Nord> AS ?NEW2S )
  BIND ( <http://semantic-forms.cc:1952/ldp/Inventaire_Saint_Didier> AS ?NEWS )
  BIND ( <http://semantic-forms.cc:1952/ldp/Saint_Didier> AS ?OLDS )
  GRAPH ?G {
    ?OLDS ?P ?O .
  }
}
