# These triples prevent correct geoparql (spatial) query in Jena 4.2.0
# Spatial coordinates must be (real ?) numbers
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT
  (COUNT(?LONG) AS ?STRINGSLONG)
  (COUNT(?LAT)  AS ?STRINGSLAT )
WHERE {
GRAPH ?G {
  {
  ?place geo:long ?LONG .
  FILTER ( datatype(?LONG) = xsd:string
        || datatype(?LONG) = rdf:langString )
  } UNION {
  ?place geo:lat ?LAT .
  FILTER ( datatype(?LAT) = xsd:string
        || datatype(?LAT) = rdf:langString )
   }
}}
