# Adding alignment triples between Wikidata and dbPedia
# query to dbpedia.org/sparql

prefix owl: <http://www.w3.org/2002/07/owl#>
prefix dbo: <http://dbpedia.org/ontology/>
# select distinct *
construct {
  ?TAX_DBPEDIA owl:sameAs ?TAX_WKDT .
  ?TAX_WKDT owl:sameAs ?TAX_DBPEDIA .
} where {
  ?TAX_DBPEDIA owl:sameAs ?TAX_WKDT .
  FILTER ( STRSTARTS( STR(?TAX_WKDT), 'http://www.wikidata.org/entity' ) )
  ?TAX_DBPEDIA a dbo:Plant .
  ?TAX_DBPEDIA a dbo:Species .
}
